# Generated by Django 5.0.6 on 2024-10-14 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0003_remove_estado_tempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='nomeestado',
            new_name='nome_estado',
        ),
    ]
