# Generated by Django 5.0.6 on 2024-10-23 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0004_rename_nomeestado_estado_nome_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estado',
            old_name='nome_estado',
            new_name='nomeestado',
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(db_index=True, default='', max_length=2, verbose_name='Sigla'),
        ),
    ]
