# Generated by Django 5.0.6 on 2024-10-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0005_rename_nome_estado_estado_nomeestado_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estado',
            table='estado',
        ),
    ]
