# Generated by Django 5.0.6 on 2024-10-23 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0006_alter_estado_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='estado',
            table='estados',
        ),
    ]
