# Generated by Django 5.0.6 on 2024-10-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0008_alter_estado_options_alter_estado_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nomeestado',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='sigla',
            field=models.CharField(db_index=True, default='', max_length=2, unique=True, verbose_name='Sigla'),
        ),
    ]
