# Generated by Django 5.0.6 on 2024-10-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomecidade', models.CharField(db_index=True, default='', max_length=65, unique=True, verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'db_table': 'cidades',
                'db_table_comment': 'Cidades do brasil',
                'indexes': [models.Index(fields=['nomecidade'], name='cidades_nomecid_80f16a_idx')],
            },
        ),
    ]
