# Generated by Django 5.0.6 on 2024-10-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(db_index=True, default='SP', max_length=2, verbose_name='Sigla')),
                ('tempo', models.CharField(db_index=True, default='SP', max_length=2, verbose_name='tempo')),
                ('nomeestado', models.CharField(db_index=True, default='', max_length=50, verbose_name='Estado')),
            ],
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
