# Generated by Django 5.0.6 on 2024-10-14 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0002_estado_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estado',
            name='tempo',
        ),
    ]
