# Generated by Django 5.0.6 on 2024-10-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estados', '0007_alter_estado_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estado',
            options={'verbose_name': 'Estado', 'verbose_name_plural': 'Estados'},
        ),
        migrations.AlterModelTableComment(
            name='estado',
            table_comment='Estados Brasileiros',
        ),
        migrations.AddIndex(
            model_name='estado',
            index=models.Index(fields=['nomeestado'], name='estados_nomeest_f3381f_idx'),
        ),
    ]
