# Generated by Django 5.0.6 on 2024-10-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fundo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundo', models.CharField(db_index=True, default='', max_length=100, unique=True, verbose_name='Fundo')),
            ],
            options={
                'verbose_name': 'Fundo',
                'verbose_name_plural': 'Fundos',
                'db_table': 'fundos',
                'db_table_comment': 'Fundos',
            },
        ),
    ]
