# Generated by Django 5.0.6 on 2024-10-11 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0011_remove_transaction_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='contato',
        ),
        migrations.AddField(
            model_name='transaction',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=150, validators=[django.core.validators.EmailValidator('Informe um endereço de e-mail correto!')], verbose_name='E-mail'),
        ),
    ]
