# Generated by Django 5.0.6 on 2024-11-05 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.CharField(default='', max_length=100, verbose_name='Arquivo')),
            ],
            options={
                'verbose_name': 'Upload',
                'verbose_name_plural': 'Uploads',
                'db_table': 'uploads',
                'db_table_comment': 'Envio de Arquivos',
            },
        ),
    ]
