# Generated by Django 5.0.6 on 2024-11-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='arquivo',
            field=models.FileField(upload_to=''),
        ),
    ]
