# Generated by Django 5.0.6 on 2024-11-09 23:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0002_alter_upload_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='arquivo',
            new_name='excel_file',
        ),
        migrations.AddField(
            model_name='upload',
            name='excel_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
