# Generated by Django 5.0.6 on 2024-10-23 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vinculo', models.CharField(db_index=True, default='', max_length=100, unique=True, verbose_name='Vinculo')),
            ],
            options={
                'verbose_name': 'Vinculo',
                'verbose_name_plural': 'Vinculos',
                'db_table': 'vinculos',
                'db_table_comment': 'Gerenciamento',
                'indexes': [models.Index(fields=['vinculo'], name='vinculos_vinculo_489a9f_idx')],
            },
        ),
    ]
