# Generated by Django 5.0.6 on 2024-11-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='AUXILIO_SAUDE',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='AUXILIO_SAUDE'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='BONUS_BEP',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='BONUS_BEP'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_CARGO',
            field=models.IntegerField(blank=True, verbose_name='CO_CARGO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_COMP_MASSA',
            field=models.IntegerField(blank=True, verbose_name='CO_COMP_MASSA'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_ESCOLARIDADE',
            field=models.IntegerField(blank=True, verbose_name='CO_ESCOLARIDADE'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_ESTCIVIL_SERVIDOR',
            field=models.IntegerField(blank=True, verbose_name='CO_ESTCIVIL_SERVIDOR'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_PODER',
            field=models.IntegerField(blank=True, verbose_name='CO_PODER'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_SEXO_SERVIDOR',
            field=models.IntegerField(blank=True, verbose_name='CO_SEXO_SERVIDOR'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_SITUACAO_FUNCIONAL',
            field=models.IntegerField(blank=True, verbose_name='CO_SITUACAO_FUNCIONAL'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_TIPO_CARGO',
            field=models.IntegerField(blank=True, verbose_name='CO_TIPO_CARGO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='CO_TIPO_VINCULO',
            field=models.IntegerField(blank=True, verbose_name='CO_TIPO_VINCULO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_ADESAO_PREV_COMP',
            field=models.DateField(blank=True, verbose_name='DT_ADESAO_PREV_COMP'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_FIM_RGPS',
            field=models.DateField(blank=True, verbose_name='DT_FIM_RGPS'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_FIM_SPUB',
            field=models.DateField(blank=True, verbose_name='DT_FIM_SPUB'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_ING_CARGO',
            field=models.DateField(blank=True, verbose_name='DT_ING_CARGO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_ING_CARREIRA',
            field=models.DateField(blank=True, verbose_name='DT_ING_CARREIRA'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_ING_SPUB',
            field=models.DateField(blank=True, verbose_name='DT_ING_SPUB'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_ING_UNIAO',
            field=models.DateField(blank=True, verbose_name='DT_ING_UNIAO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_INICIO_ABONO',
            field=models.DateField(blank=True, verbose_name='DT_INICIO_ABONO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_INICIO_RGPS',
            field=models.DateField(blank=True, verbose_name='DT_INICIO_RGPS'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='DT_NASC_SERVIDOR',
            field=models.DateField(blank=True, verbose_name='DT_NASC_SERVIDOR'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ID_SERVIDOR',
            field=models.IntegerField(blank=True, verbose_name='ID_SERVIDOR'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ID_SERVIDOR_CPF',
            field=models.CharField(blank=True, max_length=15, verbose_name='ID_SERVIDOR_CPF'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ID_SERVIDOR_MATRICULA',
            field=models.IntegerField(blank=True, verbose_name='ID_SERVIDOR_MATRICULA'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ID_SERVIDOR_PASEP',
            field=models.CharField(blank=True, max_length=15, verbose_name='ID_SERVIDOR_PASEP'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='IN_ABONO_PERMANENCIA',
            field=models.IntegerField(blank=True, verbose_name='IN_ABONO_PERMANENCIA'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='IN_BENEF_ESPECIAL',
            field=models.IntegerField(blank=True, verbose_name='IN_BENEF_ESPECIAL'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='IN_DEFICIENCIA',
            field=models.IntegerField(blank=True, verbose_name='IN_DEFICIENCIA'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='IN_EXP_NOCIVO',
            field=models.IntegerField(blank=True, verbose_name='IN_EXP_NOCIVO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='IN_PREV_COMP',
            field=models.IntegerField(blank=True, verbose_name='IN_PREV_COMP'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NO_CARGO',
            field=models.CharField(blank=True, max_length=100, verbose_name='NO_CARGO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NO_CARREIRA',
            field=models.IntegerField(blank=True, verbose_name='NO_CARREIRA'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NO_ORGAO',
            field=models.IntegerField(blank=True, verbose_name='NO_ORGAO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NO_SERVIDOR',
            field=models.CharField(blank=True, max_length=110, verbose_name='NO_SERVIDOR'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NU_ANO',
            field=models.IntegerField(blank=True, verbose_name='NU_ANO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NU_CNPJ_ORGAO',
            field=models.CharField(blank=True, max_length=20, verbose_name='NU_CNPJ_ORGAO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NU_MES',
            field=models.IntegerField(blank=True, verbose_name='NU_MES'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NU_TEMPO_CONTRIB_ADESAO',
            field=models.IntegerField(blank=True, verbose_name='NU_TEMPO_CONTRIB_ADESAO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NU_TEMPO_CONTRIB_TOTAL',
            field=models.IntegerField(blank=True, verbose_name='NU_TEMPO_CONTRIB_TOTAL'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NU_TEMPO_RGPS',
            field=models.IntegerField(blank=True, verbose_name='NU_TEMPO_RGPS'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='NU_TEMPO_RPPS',
            field=models.IntegerField(blank=True, verbose_name='NU_TEMPO_RPPS'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_BASE_CALCULO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_BASE_CALCULO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_BENEFICIO_ESPECIAL',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_BENEFICIO_ESPECIAL'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_CONTRIBUICAO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_CONTRIBUICAO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_REMUNERACAO',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_REMUNERACAO'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_REMUNERACAO_1994',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_REMUNERACAO_1994'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_REMUNERACAO_2003',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_REMUNERACAO_2003'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_REMUNERACAO_2014',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_REMUNERACAO_2014'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='VL_REMUNERACAO_2019',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='VL_REMUNERACAO_2019'),
        ),
    ]
