# Generated by Django 5.0.6 on 2024-11-10 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servidores', '0002_alter_servidor_auxilio_saude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servidor',
            name='ID_SERVIDOR_CPF',
            field=models.IntegerField(blank=True, max_length=15, verbose_name='ID_SERVIDOR_CPF'),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='ID_SERVIDOR_PASEP',
            field=models.IntegerField(blank=True, max_length=15, verbose_name='ID_SERVIDOR_PASEP'),
        ),
    ]
