# Generated by Django 5.0.6 on 2024-10-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(db_index=True, default='', max_length=100, unique=True, verbose_name='Dependência')),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependecias',
                'db_table': 'dependencias',
                'db_table_comment': 'Tipos de Dependências',
            },
        ),
    ]
