# Generated by Django 5.0.6 on 2024-10-23 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estadocivil', models.CharField(db_index=True, default='', max_length=30, unique=True, verbose_name='Estado Civil')),
            ],
            options={
                'verbose_name': 'EstadoCivil',
                'verbose_name_plural': 'EstadosCivis',
                'db_table': 'estadoscivis',
                'db_table_comment': 'Estado Civil das pessoas',
            },
        ),
    ]
