# Generated by Django 5.0.6 on 2024-10-23 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='cargo',
            field=models.CharField(db_index=True, default='', max_length=100, unique=True, verbose_name='Cargo'),
        ),
    ]
