# Generated by Django 5.0.6 on 2024-10-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poder', models.CharField(db_index=True, default='', max_length=30, unique=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Poder',
                'verbose_name_plural': 'Poderes',
                'db_table': 'poderes',
                'db_table_comment': 'Poderes',
                'indexes': [models.Index(fields=['poder'], name='poderes_poder_f0aa05_idx')],
            },
        ),
    ]
