# Generated by Django 5.0.6 on 2024-10-23 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poderes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poder',
            name='poder',
            field=models.CharField(db_index=True, default='', max_length=30, unique=True, verbose_name='Poder'),
        ),
    ]
